url: https://entrepreneurs.berkeley.edu/
baseurl:

# Site settings
title: Entrepreneurs@Berkeley
email: admin@entrepreneurs.berkeley.edu
description: UC Berkeley's Premier hub for entrepenership. Bringing together founders, innovators, and dreamers. Open to all majors and years


# Team names, titles and social links
people:

- name: Sahil Mehta
  pic: sahil
  position: Co-President
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/sahil-mehta-412783190/
    - title: envelope
      url: mehtasahil881@berkeley.edu

- name: Nick Lai
  pic: nick_lai
  position: Co-President
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/nickplai/
    - title: envelope
      url: nickplai@berkeley.edu


- name: Khushi Malde
  pic: khushi
  position: Operations VP
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/khushi-malde/
    - title: envelope
      url: khushimalde@berkeley.edu

- name: Max Kim
  pic: max
  position: Operations VP
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/max-kim-371903194/
    - title: envelope
      url: maxkim@berkeley.edu


- name: Rachel Moy
  pic: rachel
  position: Marketing VP
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/rachelkarminmoy/
    - title: envelope
      url: rachelmoy@berkeley.edu


- name: Dyllan Liu
  pic: dyllan_liu
  position: Finance VP
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/dyllan-liu-02ab4018a/
    - title: envelope
      url: dyllan2001@berkeley.edu


- name: Serena Cheng
  pic: serena_cheng
  position: Public Relations VP
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/xiqun-cheng-71308b169/
    - title: envelope
      url: xiquncheng@berkeley.edu





# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/EntrepreneursAtBerkeley
  - title: instagram
    url: https://www.instagram.com/entrepreneursberkeley/
  - title: linkedin
    url: https://www.linkedin.com/company/entrepreneurs-berkeley

# Postal address (add as many lines as necessary)
# address:
#   - line: 3481 Melrose Place
#   - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
