url: https://entrepreneurs.berkeley.edu/
baseurl:

# Site settings
title: Entrepreneurs@Berkeley
email: admin@entrepreneurs.berkeley.edu
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Ashley Aikman
  pic: ashley_aikman_mugshot
  position: Finance Committee Member
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Clark Wang
  pic: clark_wang_mugshot
  position: Technology Committee Member
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Emily (Ying) Wang
  pic: emily_ying_mugshot
  position: Marketing Committee Member
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Enrique Santos
  pic: enrique
  position: Finance Committee Member
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Henry Cheong
  pic: henry_cheong_mugshot
  position: Finance Committee Member
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: James Wang
  pic: james_wang_mugshot
  position: Finance Committee Member
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Katherine Zhao
  pic: katherine_zhao
  position: Marketing Committee Member
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #]

- name: Michael Wu
  pic: michael_wu_mugshot
  position: Technology Committee Member
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Neil Qiao
  pic: neil_qiao
  position: Outreach Committee Member
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Raghav Mittal
  pic: raghav_mittal_mugshot
  position: Finance Committee Member
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Raja Riahi
  pic: raja_riahi_mugshot
  position: Outreach Committee Member
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Rimika Banerjee
  pic: rimika_banerjee_mugshot
  position: Technology Committee Member
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/EntrepreneursAtBerkeley
  - title: instagram
    url: https://www.instagram.com/entrepreneursberkeley/
  - title: linkedin
    url: https://www.linkedin.com/company/entrepreneurs-berkeley

# Postal address (add as many lines as necessary)
# address:
#   - line: 3481 Melrose Place
#   - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
