url: https://entrepreneurs.berkeley.edu/
baseurl:

# Site settings
title: Entrepreneurs@Berkeley
email: admin@entrepreneurs.berkeley.edu
description: UC Berkeley's Premier hub for entrepenership. Bringing together founders, innovators, and dreamers. Open to all majors and years


# Team names, titles and social links
people:

- name: Michael Wu
  pic: michael_wu_mugshot
  position: Co-President
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/michael-wu-50417610a/
    - title: envelope
      url: wuxiaohua1011@berkeley.edu

- name: Henry Cheong
  pic: henry_cheong_mugshot
  position: Internal Operations VP
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/henry-cheong/
    - title: envelope
      url: cheongh@berkeley.edu

- name: Katherine Zhao
  pic: katherine_zhao
  position: Finance VP
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/katherine-zhao/
    - title: envelope
      url: katherine_zhao@berkeley.edu

- name: Rimika Banerjee
  pic: rimika_banerjee_mugshot
  position: Public Relations VP
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/rimika-banerjee/
    - title: envelope
      url: rimikabanerjee@entrepreneurs.berkeley.edu

- name: Elaine Gao
  pic: elaine_mugshot
  position: Marketing VP
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/elaine-gao-95653516a
    - title: envelope
      url: elainegao888@berkeley.edu

- name: Atharva Mehendale
  pic: atharva_mehendale_mugshot
  position: Operations Member
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/atharvamehendale/
    - title: envelope
      url: atharva@berkeley.edu


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/EntrepreneursAtBerkeley
  - title: instagram
    url: https://www.instagram.com/entrepreneursberkeley/
  - title: linkedin
    url: https://www.linkedin.com/company/entrepreneurs-berkeley

# Postal address (add as many lines as necessary)
# address:
#   - line: 3481 Melrose Place
#   - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
